services:
  #SchoolDataTable
  sms.datatable.feature:
      class: SMS\SchoolBundle\SchoolDatatable\FeatureDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.pricing:
      class: SMS\SchoolBundle\SchoolDatatable\PricingDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.pricingFeature:
      class: SMS\SchoolBundle\SchoolDatatable\PricingFeatureDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.slider:
      class: SMS\SchoolBundle\SchoolDatatable\SliderDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.contact:
      class: SMS\SchoolBundle\SchoolDatatable\ContactDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.aboutUs:
      class: SMS\SchoolBundle\SchoolDatatable\AboutUsDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.schoolTestimonial:
      class: SMS\SchoolBundle\SchoolDatatable\SchoolTestimonialDatatable
      parent: sg_datatables.datatable.abstract
  form.type.translatable:
    class: SMS\SchoolBundle\Form\FormType\TranslatedFieldType
    arguments: [ @service_container ]
    tags:
      - { name: form.type, alias: sms_translatable_field }
  sms.school.entity_manager:
      class: SMS\SchoolBundle\Services\SchoolEntityManager
      arguments: ["@doctrine.orm.entity_Manager" ]
