imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sms_param.yml }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
framework:
    esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    assets:
        version: 'v0.1'
        version_format: '%%s?v=%%s'
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true
# assetic Configuration
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    assets:
        base_css:
            inputs:
                - 'assets/css/uikit.almost-flat.min.css'
                - 'assets/icons/flags/flags.min.css'
                - 'assets/css/main.fix.min.css'
                - 'assets/css/themes/themes_combined.min.css'
                - 'https://fonts.googleapis.com/css?family=Source+Code+Pro:400,700:latin'
                - 'https://fonts.googleapis.com/css?family=Roboto:400,300,500,700,400italic:latin'
# Twig Configuration
twig:
    globals:
        app_name: '%app_name%'
        msg_success: '%flash_msg_success%'
        msg_danger: '%flash_msg_error%'
        attendance_professor: '%attendance_professor%'
        attendance_section: '%attendance_section%'
        logo: '%logo%'
        days: '%days%'
        months: '%months%'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - "form/form.html.twig"
# Doctrine Configuration

doctrine:
    dbal:
        default_connection: default
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            string_functions:
                GROUP_CONCAT: API\DoctrineExtensions\GroupConcat
                DATE_FORMAT: API\DoctrineExtensions\DateFormat
                CONCAT_WS: API\DoctrineExtensions\ConcatWs
                MONTH: API\DoctrineExtensions\Month
        mappings:
            translatable:
                type: annotation
                is_bundle: false
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: GedmoTranslatable
            translator:
                type: annotation
                prefix: Gedmo\Translator\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                is_bundle: false
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
# knp_paginator Configuration
knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: Pagination/sliding.html.twig      # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template
# vich_uploader Configuration
vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: false
    mappings:
        user_image:
            uri_prefix:         /images/user_img
            upload_destination: '%kernel.root_dir%/../web/images/user_img'
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        app_image:
            uri_prefix:         /images/app_img
            upload_destination: '%kernel.root_dir%/../web/images/app_img'
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        store_image:
            uri_prefix:         /images/store_image
            upload_destination: '%kernel.root_dir%/../web/images/store_image'
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        establishment_logo:
            uri_prefix:         /images/establishment_logo
            upload_destination: '%kernel.root_dir%/../web/images/establishment_logo'
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
# knp_menu Configuration
knp_menu:
    twig:
        template: KnpMenuBundle::menu.html.twig
    templating: false
    default_renderer: twig
# knp_snappy Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     %kernel.root_dir%/../wkhtmltox-amd64/bin/wkhtmltopdf-amd64
        options:    []
    image:
        enabled:    true
        binary:     %kernel.root_dir%/../wkhtmltox-amd64/bin/wkhtmltoimage-amd64 #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []
    temporary_folder: %kernel.cache_dir%/snappy
# stof_doctrine_extensions Configuration
stof_doctrine_extensions:
    default_locale: '%locale%'
    translation_fallback: true
    orm:
        default:
            translatable: true

sg_datatables:
    datatable:
        query:
            translation_query_hints: true
