#datatable
services:
    sms.datatable.grade:
        class: API\Datatables\EstablishmentDatatable\GradeDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.section:
        class: API\Datatables\EstablishmentDatatable\SectionDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.division:
        class: API\Datatables\EstablishmentDatatable\DivisionDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.administrator:
        class: API\Datatables\UserDatatable\AdministratorDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.professor:
        class: API\Datatables\UserDatatable\ProfessorDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.student:
        class: API\Datatables\UserDatatable\StudentDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.student_parent:
        class: API\Datatables\UserDatatable\StudentParentDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.session:
        class: API\Datatables\StudyPlanDatatable\SessionDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.day:
        class: API\Datatables\StudyPlanDatatable\DayDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.session:
        class: API\Datatables\StudyPlanDatatable\SessionDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.course:
        class: API\Datatables\StudyPlanDatatable\CourseDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.exam:
        class: API\Datatables\StudyPlanDatatable\ExamDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.note:
        class: API\Datatables\StudyPlanDatatable\NoteDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.type_exam:
        class: API\Datatables\StudyPlanDatatable\TypeExamDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.schedule:
        class: API\Datatables\StudyPlanDatatable\ScheduleDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.attendance:
        class: API\Datatables\AdministrativeDatatable\AttendanceDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.sanction:
        class: API\Datatables\AdministrativeDatatable\SanctionDatatable
        parent: sg_datatables.datatable.abstract
