sms_payment_catch_up_lesson:
    resource: "@SMSPaymentBundle/Controller/CatchUpLessonController.php"
    type:     annotation

sms_store:
    resource: "@SMSStoreBundle/Controller/"
    type:     annotation
    prefix:   /

sms_payment:
    resource: "@SMSPaymentBundle/Controller/"
    type:     annotation
    prefix:   /

sms_school:
    resource: "@SMSSchoolBundle/Controller/"
    type:     annotation
    prefix:   /

sms_user_space:
    resource: "@SMSUserSpaceBundle/Controller/"
    type:     annotation
    prefix:   /

sms_administrative:
    resource: "@SMSAdministrativeBundle/Controller/"
    type:     annotation
    prefix:   /

sms_user:
    resource: "@SMSUserBundle/Controller/"
    type:     annotation
    prefix:   /

sms_study_plan:
    resource: "@SMSStudyPlanBundle/Controller/"
    type:     annotation
    prefix:   /

sms_establishment:
    resource: "@SMSEstablishmentBundle/Controller/"
    type:     annotation
    prefix:   /

sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

datatables:
    resource: "@DatatablesBundle/Controller/"
    type:     annotation
    prefix:   /

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans
