# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        SMS\UserBundle\Entity\User:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_STUDENT: ROLE_STUDENT
        ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN
        ROLE_PARENT: ROLE_PARENT
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_PROFESSOR: ROLE_PROFESSOR
        ROLE_MANAGER: ROLE_MANAGER
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: SMSUserBundle:User
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            anonymous: ~
            provider: our_db_provider
            logout:
                path:   user_logout
                target: login
                invalidate_session: true
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: login
                check_path: login
                post_only: true
                success_handler:     login_success_handler
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
