# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
    sms.entity_manager:
        class: API\Services\EntityManager
        arguments: ["@doctrine.orm.entity_Manager" , '@security.token_storage' ]
        calls:
          - [setMailer, ['@sms.mailer']]
    sms.store_manager:
        class: API\Services\StoreManager
        arguments: ["@doctrine.orm.entity_Manager" ]
    sms.user_space:
        class: API\Services\UserSpaceManager
        arguments: ["@doctrine.orm.entity_Manager"]
        calls:
            - [ setDays , ["%days%"]]
    sms.mailer:
        class: API\Services\Mailer
        arguments: ["@mailer" , "@templating"]
        calls:
          - method: setEmail
            arguments:
              - "%mailer_user%"
    #listener
    #sms.exception_listener:
        #class: API\EventListener\ExceptionListener
        #tags:
            #- { name: kernel.event_listener, event: kernel.exception }
    kernel.listener.CacheListener:
        class: API\EventListener\CacheListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    #user.onligne_user_listener:
        #class: API\EventListener\OnligneUserListener
        #arguments: [@security.context, @sms.user.entity_manager]
        #tags:
            #- { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
    sms.locale_listener:
        class: API\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    sms.security_listener:
        class: API\EventListener\AfterLoginListener
        arguments: ['@session' , '%Establishment%']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
    # menu builder
    sms.menu_builder:
        class: API\Menu\MenuBuilder
        arguments: ["@knp_menu.factory" , "@security.authorization_checker" , "@security.context"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }
    sms.form.type.day:
        class: API\Form\Type\DayType
        arguments:
            - '%days%'
        tags:
            - { name: form.type }
    sms.form.type.month:
        class: API\Form\Type\MonthType
        arguments:
            - '%months%'
        tags:
              - { name: form.type }
    sms.form.hidden_entity:
        class: API\Form\Type\HiddenEntityType
        arguments: ['@doctrine.orm.entity_Manager']
        tags:
            - { name: form.type }
