parameters:
    flash_msg_success: '_msg_success'
    flash_msg_error: '_msg_error'
    tokenLifetime: 21600
    app_name: 'schoolarz v0.1'
    logo: establishmentLogo
    # mailer
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ramisfari22@gmail.com
    mailer_password: ramisfari123
    # attendance status
    attendance_section:
        R  : Retard
        P  : Present
        A  : Absent
        E  : Exclude
    attendance_professor:
        R  : Retard
        P  : Present
        A  : Absent
    # days
    days:
      Monday: day.monday
      Tuesday: day.tuesday
      Wednesday: day.wednesday
      Thursday: day.thursday
      Friday: day.friday
      Saturday: day.saturday
      Sunday: day.sunday
    months:
      01: month.january
      02: month.february
      03: month.march
      04: month.april
      05: month.may
      06: month.june
      07: month.july
      08: month.august
      09: month.september
      10: month.october
      11: month.november
      12: month.december
