services:
  #Services
  sms.study_plan.entity_manager:
      class: SMS\StudyPlanBundle\Services\StudyPlanManager
      arguments: ["@doctrine.orm.entity_Manager" ]
      calls:
          - [ setDays , [%days%]]
          - [ setSectionClass , [SMS\EstablishmentBundle\Entity\Section]]
          - [ setGradeClass , [SMS\EstablishmentBundle\Entity\Grade]]
          - [ setSessionClass , [SMS\StudyPlanBundle\Entity\Session]]
          - [ setScheduleClass , [SMS\StudyPlanBundle\Entity\Schedule]]
          - [ setStudentClass , [SMS\UserBundle\Entity\Student]]
          - [ setProfessorClass , , [SMS\UserBundle\Entity\Professor]]
          - [ setExamTypeClass , [SMS\StudyPlanBundle\Entity\TypeExam]]
          - [ setCourseClass , [SMS\StudyPlanBundle\Entity\Course]]
          - [ setExamClass , [SMS\StudyPlanBundle\Entity\Exam]]
          - [ setNoteClass , [SMS\StudyPlanBundle\Entity\Note]]

  #Datatables
  sms.datatable.section_manager:
      class: SMS\StudyPlanBundle\Datatables\SectionManagerDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.session:
      class: SMS\StudyPlanBundle\Datatables\SessionDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.course:
      class: SMS\StudyPlanBundle\Datatables\CourseDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.exam:
      class: SMS\StudyPlanBundle\Datatables\ExamDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.note:
      class: SMS\StudyPlanBundle\Datatables\NoteDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.type_exam:
      class: SMS\StudyPlanBundle\Datatables\TypeExamDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.schedule:
      class: SMS\StudyPlanBundle\Datatables\ScheduleDatatable
      parent: sg_datatables.datatable.abstract
  #form
  sms.form.type.schedule:
      class: SMS\StudyPlanBundle\Form\ScheduleType
      arguments:
          - '@doctrine.orm.entity_Manager'
      tags:
          - { name: form.type }
  sms.form.type.search:
      class: SMS\StudyPlanBundle\Form\SearchType
      arguments:
          - '@doctrine.orm.entity_Manager'
      tags:
          - { name: form.type }
  sms.form.type.exam_student:
      class: SMS\StudyPlanBundle\Form\ExamFilterType
      arguments:
          - '@doctrine.orm.entity_Manager'
      tags:
          - { name: form.type }
  sms.form.type.schedule_student:
      class: SMS\StudyPlanBundle\Form\ScheduleStudentFilterType
      arguments:
          - '@doctrine.orm.entity_Manager'
      tags:
          - { name: form.type }
  sms.form.type.exam:
      class: SMS\StudyPlanBundle\Form\ExamType
      arguments:
          - '@doctrine.orm.entity_Manager'
      tags:
          - { name: form.type }
  sms.form.type.note:
      class: SMS\StudyPlanBundle\Form\NoteType
      arguments:
          - '@doctrine.orm.entity_Manager'
      tags:
          - { name: form.type }
