parameters:
  #datatable
  payment_datatable: SMS\PaymentBundle\PaymentDatatable\PaymentDatatable
  payment_type_datatable: SMS\PaymentBundle\PaymentDatatable\PaymentTypeDatatable
  registration_datatable: SMS\PaymentBundle\PaymentDatatable\RegistrationDatatable
  registration_users_datatable: SMS\PaymentBundle\PaymentDatatable\StudentDatatable
  #payment_form
  payment_form: SMS\PaymentBundle\Form\PaymentType
  registration_form: SMS\PaymentBundle\Form\RegistrationType
  #services
  payment_entity_manager: SMS\PaymentBundle\Services\PaymentEntityManager
  payment_mail_manager: SMS\PaymentBundle\Services\Mailer
  payment_template: SMSPaymentBundle:email:payment.html.twig
  registration_template: SMSPaymentBundle:email:registration.html.twig
  #Dependency Injection class
  payment_type_class: SMS\PaymentBundle\Entity\PaymentType
  registration_type_class: SMS\PaymentBundle\Entity\RegistrationType
  #Dependency Injection class
  student_class: SMS\UserBundle\Entity\Student
  grade_class: SMS\EstablishmentBundle\Entity\Grade
  section_class: SMS\EstablishmentBundle\Entity\Section
  establishment_class: SMS\EstablishmentBundle\Entity\Establishment
