services:
  #User Datatable
  sms.datatable.manager:
      class: %user_manager_class%
      parent: sg_datatables.datatable.abstract
  sms.datatable.administrator:
      class: %user_administrator_class%
      parent: sg_datatables.datatable.abstract
  sms.datatable.professor:
      class: %user_professor_class%
      parent: sg_datatables.datatable.abstract
  sms.datatable.student:
      class: %user_student_class%
      parent: sg_datatables.datatable.abstract
  sms.datatable.student_parent:
      class: %user_parent_class%
      parent: sg_datatables.datatable.abstract
  #Services
  sms.user.entity_manager:
      class: %user_entity_manager%
      arguments: ["@doctrine.orm.entity_Manager" , "@security.password_encoder" , '@security.token_storage']
      calls:
        - [setMailer, ['@sms.user.mailer']]
  sms.user.mailer:
      class: %user_mail_manager%
      arguments: ["@mailer" , "@templating"]
      calls:
        - [setEmail, ["%mailer_user%"]]
        - [setResettingTemplatePath, ["%resetting_template%"]]
        - [setRegistrationTemplatePathWithPassword, ["%registration_template_with_password%"]]
        - [setRegistrationTemplatePathWithOutPassword, ["%registration_template_without_password%"]]
  #Forms
  sms.form.student_parent:
      class: %form_user_parent_class%
      arguments: ['@security.token_storage']
      tags:
          - { name: form.type }
  sms.form.administrator:
      class: %form_user_administrator_class%
      arguments: ['@security.token_storage']
      tags:
          - { name: form.type }
  sms.form.professor:
      class: %form_user_professor_class%
      arguments: ['@security.token_storage']
      tags:
          - { name: form.type }
  sms.form.student:
      class: %form_user_student_class%
      arguments: ['@security.token_storage' , "@doctrine.orm.entity_Manager"]
      tags:
          - { name: form.type }
  #form type
  sms.form.type.role:
      class: %user_role_type%
      arguments:
          - '%security.role_hierarchy.roles%'
      tags:
          - { name: form.type }
