services:
  #EstablishmentDatatable
  sms.datatable.grade:
      class: SMS\EstablishmentBundle\EstablishmentDatatable\GradeDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.section:
      class: SMS\EstablishmentBundle\EstablishmentDatatable\SectionDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.division:
      class: SMS\EstablishmentBundle\EstablishmentDatatable\DivisionDatatable
      parent: sg_datatables.datatable.abstract
  sms.datatable.establishment:
      class: SMS\EstablishmentBundle\EstablishmentDatatable\EstablishmentDatatable
      parent: sg_datatables.datatable.abstract
  #Services
  sms.establishment.entity_manager:
      class: SMS\EstablishmentBundle\Services\EstablishmentEntityManager
      arguments: [@doctrine.orm.entity_Manager , @translator ]
      calls:
          - [ setSectionClass , [SMS\EstablishmentBundle\Entity\Section]]
          - [ setStudentClass , [SMS\UserBundle\Entity\Student]]
          - [ setProfessorClass , [SMS\UserBundle\Entity\Professor]]
          - [ setCourseClass , [SMS\StudyPlanBundle\Entity\Course]]
