services:
    sms.datatable.grade:
        class: SMS\EstablishmentBundle\Datatables\GradeDatatable
        parent: sg_datatables.datatable.abstract
    sms.datatable.section:
        class: SMS\EstablishmentBundle\Datatables\SectionDatatable
        parent: sg_datatables.datatable.abstract